### ISSUE TITLE
Discrepancy with .NET (www is added on .online-URLs)

### ISSUE THREAD

**Issue by roback** [twingly/twingly-url#143] opened 2020-04-29 13:04 UTC
Our .NET normalizer does not add `www.` when normalizing a `.online` URL, while twingly-url does that:

```
$ echo "http://test.online/" | mono trunk/Deploy/Normalizer/Normalizer.exe
http://test.online/,http://test.online/,10236098798714371386
$ ruby -rtwingly/url -e 'puts Twingly::URL.parse("http://test.online/").normalized'
http://www.test.online/
```

`.online` is most likely not the only one...

**Comment by walro** [comment] 2020-04-29 13:15
I would argue we should fix this in .NET actually.

**Comment by walro** [comment] 2020-06-04 11:08
I will close this, I think it works as intended. We will keep the issue for our "legacy systems".

**Closed by walro** 2020-06-04 11:08 UTC
Labels: bug
